version: '3.8'

services:
  app:
    build: .
    container_name: etl_app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - postgres
    networks:
      - etl_network
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - etl_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  etl_network:

volumes:
  postgres_data:
